name: MkDocs-deploy
on:
  push:
    branches:
      - main
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install the requirements
        shell: bash -l {0}
        run: |
          pip3 install -r requirements.txt
      # Run the python scripts   
      - name: Run literature_fetch
        shell: bash -l {0}
        run: |
          python3 app/algorithms/table.py  
          pyhton3 app/data/markdown_report.py
          python3 app/leaderboard/table.py
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --clean --force 