name: Validation Workflow

# Trigger on pull requests and manual workflow dispatch
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'vpeleaderboard/data/src/sbml/models/**'
      - 'vpeleaderboard/configs/data**'
  workflow_dispatch:

jobs:
  validate-ubuntu-macos:
    name: Validate Models and Configs on Ubuntu/macOS
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Debug directory contents
        run: |
          echo "📂 Listing model XML files:"
          ls -l vpeleaderboard/data/src/sbml/models/ || echo "No models found"
          echo "📂 Listing config YAML files:"
          ls -l vpeleaderboard/configs/data/ || echo "No configs found"    

      - name: Validate XML/YAML file presence and naming
        id: validate
        run: |
          echo "🔍 Validating XML and YAML files on ${{ matrix.os }}..."

          models_files=$(ls vpeleaderboard/data/src/sbml/models/ -iname '*.xml' 2>/dev/null || true)
          configs_files=$(ls vpeleaderboard/configs/data/*.yaml 2>/dev/null || true)

          models=""
          if [ -n "$models_files" ]; then
            models=$(echo "$models_files" | xargs -n 1 basename | sed 's/.xml$//')
          fi

          configs=""
          if [ -n "$configs_files" ]; then
            configs=$(echo "$configs_files" | xargs -n 1 basename | sed 's/.yaml$//')
          fi

          echo "📦 Models found: $models"
          echo "📦 Configs found: $configs"

          missing=false
          for model in $models; do
            if ! echo "$configs" | grep -q "^$model$"; then
              echo "❌ Missing YAML for model: $model"
              missing=true
            fi
          done

          for config in $configs; do
            if ! echo "$models" | grep -q "^$config$"; then
              echo "❌ Missing XML for config: $config"
              missing=true
            fi
          done

          if [ "$missing" = true ]; then
            echo "⛔ Validation failed. Ensure matching XML and YAML files exist."
            exit 1
          fi
  validate-windows:
    name: Validate Models and Configs on Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Validate XML/YAML file presence and naming
        id: validate
        shell: pwsh
        run: |
          echo "🔍 Validating XML and YAML files on Windows..."
          $models = Get-ChildItem "vpeleaderboard\data\src\sbml\models\*.xml" | ForEach-Object { $_.BaseName }
          $configs = Get-ChildItem "vpeleaderboard\configs\data\*.yaml" | ForEach-Object { $_.BaseName }

          $missing = $false
          foreach ($model in $models) {
            if ($configs -notcontains $model) {
              Write-Host "❌ Missing YAML for model: $model"
              $missing = $true
            }
          }

          foreach ($config in $configs) {
            if ($models -notcontains $config) {
              Write-Host "❌ Missing XML for config: $config"
              $missing = $true
            }
          }

          if ($missing) {
            Write-Host "⛔ Validation failed. Ensure matching XML and YAML files exist."
            exit 1
          }
